- name: Cleanup
  # TODO: change to remote if you have one
  hosts: local
  become: true
  tasks:
    - name: Delete user
      ansible.builtin.user:
        name: "{{ java_user_name }}"
        state: absent
        remove: yes
    - name: Remove packages
      apt:
        name: "{{ item }}"
        state: absent
      loop: "{{ packages }}"
    - name: Stop sample.service
      ansible.builtin.systemd:
        name: sample.service
        state: stopped
        enabled: no
    - name: Remove sample.service
      ansible.builtin.file:
        path: /etc/systemd/system/sample.service
        state: absent
    - name: Reload Systemd
      ansible.builtin.systemd:
        daemon_reload: yes
    - name: Force delete Unit
      ansible.builtin.shell: systemctl reset-failed
    - name: Remove {{ app_dir }}/{{ app_file }}
      ansible.builtin.file:
        path: "{{ app_dir }}/{{ app_file }}"
        state: absent